url: https://alcatraz62.github.io
baseurl: /github-pages-with-jekyll
theme: minima
title: Jekyll Demo
author: ALcatraz62
email: your-email@domain.com
description: This is a demo blog using GitHub and Jekyll.

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
